// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// to_lower_v1
String to_lower_v1(String x);
RcppExport SEXP _pedercplus_to_lower_v1(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(to_lower_v1(x));
    return rcpp_result_gen;
END_RCPP
}
// to_lower_v2
String to_lower_v2(String x);
RcppExport SEXP _pedercplus_to_lower_v2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(to_lower_v2(x));
    return rcpp_result_gen;
END_RCPP
}
// to_lower_v3
String to_lower_v3(String x);
RcppExport SEXP _pedercplus_to_lower_v3(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(to_lower_v3(x));
    return rcpp_result_gen;
END_RCPP
}
// ar1_cpp
NumericVector ar1_cpp(int n, double phi, double sigma);
RcppExport SEXP _pedercplus_ar1_cpp(SEXP nSEXP, SEXP phiSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(ar1_cpp(n, phi, sigma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pedercplus_to_lower_v1", (DL_FUNC) &_pedercplus_to_lower_v1, 1},
    {"_pedercplus_to_lower_v2", (DL_FUNC) &_pedercplus_to_lower_v2, 1},
    {"_pedercplus_to_lower_v3", (DL_FUNC) &_pedercplus_to_lower_v3, 1},
    {"_pedercplus_ar1_cpp", (DL_FUNC) &_pedercplus_ar1_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_pedercplus(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
