# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Versjon 1: std::transform med ::tolower
#'
#' @param x En tekststreng
#' @return Strengen med små bokstaver
#' @examples
#' to_lower_v1("Hello World")
#' @export
to_lower_v1 <- function(x) {
    .Call(`_pedercplus_to_lower_v1`, x)
}

#' Versjon 2: manuell loop med ASCII-aritmetikk
#'
#' Store bokstaver A-Z har ASCII 65-90, små a-z har 97-122 (avstand 32).
#'
#' @param x En tekststreng
#' @return Strengen med små bokstaver
#' @examples
#' to_lower_v2("Hello World")
#' @export
to_lower_v2 <- function(x) {
    .Call(`_pedercplus_to_lower_v2`, x)
}

#' Versjon 3: range-based for-loop med referanse
#'
#' @param x En tekststreng
#' @return Strengen med små bokstaver
#' @examples
#' to_lower_v3("Hello World")
#' @export
to_lower_v3 <- function(x) {
    .Call(`_pedercplus_to_lower_v3`, x)
}

#' Simuler en AR(1)-prosess
#'
#' Hvert steg: x(t) = phi * x(t-1) + støy.
#' Fordi hvert steg avhenger av forrige kan ikke R vektorisere dette.
#'
#' @param n   Antall tidssteg
#' @param phi Autokorrelasjon (-1 til 1). 0.9 = treg mean-reversion
#' @param sigma Standardavvik på støyen
#' @return Numerisk vektor av lengde n
#' @examples
#' set.seed(1)
#' x <- ar1_cpp(100, phi = 0.9, sigma = 1)
#' plot(x, type = "l")
#' @export
ar1_cpp <- function(n, phi, sigma) {
    .Call(`_pedercplus_ar1_cpp`, n, phi, sigma)
}

